syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.linbit.linstor.api.grpc";
option java_outer_classname = "ControllerProto";

package linbit.linstor;

import "auth_token.proto";
import "common.proto";
import "controller_data.proto";
import "node.proto";
import "resource_group.proto";

// grpc API version: 0.1.0
service Controller {
  rpc NodeList(NodeListRequest) returns (NodeListResponse);
  rpc NodeCreate(NodeCreateRequest) returns (stream Answer);
  rpc NodeModify(NodeModifyRequest) returns (stream Answer);
  rpc NodeDelete(NodeDeleteRequest) returns (stream Answer);
  rpc NodeReconnect(NodeReconnectRequest) returns (stream Answer);
  rpc ResourceGroupList(ResourceGroupListRequest) returns (ResourceGroupListResponse);
  rpc ResourceGroupCreate(ResourceGroupCreateRequest) returns (stream Answer);
  rpc ResourceGroupModify(ResourceGroupModifyRequest) returns (stream Answer);
  rpc ResourceGroupDelete(ResourceGroupDeleteRequest) returns (stream Answer);
  rpc ResourceGroupSpawn(ResourceGroupSpawnRequest) returns (stream Answer);
  rpc ResourceGroupAdjust(ResourceGroupAdjustRequest) returns (stream Answer);
  rpc ResourceGroupAdjustAll(ResourceGroupAdjustAllRequest) returns (stream Answer);
  // failures of the query itself are reported in QuerySizeInfoResponse.reports
  rpc ResourceGroupQuerySizeInfo(ResourceGroupQuerySizeInfoRequest) returns (QuerySizeInfoResponse);
  rpc ResourceGroupQueryAllSizeInfo(ResourceGroupQueryAllSizeInfoRequest)
      returns (ResourceGroupQueryAllSizeInfoResponse);
  rpc VolumeGroupList(VolumeGroupListRequest) returns (VolumeGroupListResponse);
  rpc VolumeGroupCreate(VolumeGroupCreateRequest) returns (stream Answer);
  rpc VolumeGroupModify(VolumeGroupModifyRequest) returns (stream Answer);
  rpc VolumeGroupDelete(VolumeGroupDeleteRequest) returns (stream Answer);
  rpc ControllerPropsList(ControllerPropsListRequest) returns (ControllerPropsListResponse);
  rpc ControllerPropsModify(ControllerPropsModifyRequest) returns (stream Answer);
  rpc ControllerVersion(ControllerVersionRequest) returns (ControllerVersionResponse);
  rpc ControllerConfigGet(ControllerConfigGetRequest) returns (ControllerConfigGetResponse);
  rpc ControllerConfigModify(ControllerConfigModifyRequest) returns (stream Answer);
  rpc ControllerPropsInfoList(ControllerPropsInfoListRequest) returns (ControllerPropsInfoListResponse);
  rpc ControllerDatabaseExport(ControllerDatabaseExportRequest) returns (stream Answer);
  // the new token is returned in Answer.obj_refs["token"]
  rpc AuthTokenInitialize(AuthTokenInitializeRequest) returns (stream Answer);
  rpc AuthTokenList(AuthTokenListRequest) returns (AuthTokenListResponse);
  // the new token is returned in Answer.obj_refs["token"]
  rpc AuthTokenCreate(AuthTokenCreateRequest) returns (stream Answer);
  rpc AuthTokenModify(AuthTokenModifyRequest) returns (stream Answer);
  rpc AuthTokenRevoke(AuthTokenRevokeRequest) returns (stream Answer);
}
